<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="createTable"
           tests="8"
           failures="1"
           errors="0"
           skipped="0"
           time="25.540">
  <properties />
            <testcase name="updateTable" time="0.001" classname="TestCases.testUpdateTable">
                <failure type="org.json.JSONException"
                  message="A JSONObject text must begin with &apos;{&apos; at 1 [character 2 line 1]"
              >
<![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
  org.json.JSONTokener.syntaxError(JSONTokener.java:451)
  org.json.JSONObject.<init>(JSONObject.java:195)
  org.json.JSONObject.<init>(JSONObject.java:319)
  com.peersafe.chainsql.util.Util.StrToJsonStr(Util.java:25)
  com.peersafe.chainsql.core.Table.get(Table.java:118)
  TestCases.testUpdateTable.updateTable(testUpdateTable.java:41)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.runSuites(TestNG.java:1028)
  org.testng.TestNG.run(TestNG.java:996)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="updateTable" time="0.778" classname="TestCases.testUpdateTable" />
                <testcase name="updateTable" time="6.823" classname="TestCases.testUpdateTable" />
                <testcase name="updateTable" time="0.229" classname="TestCases.testUpdateTable" />
                <testcase name="updateTable" time="0.227" classname="TestCases.testUpdateTable" />
                <testcase name="updateTable" time="6.021" classname="TestCases.testUpdateTable" />
                <testcase name="updateTable" time="5.914" classname="TestCases.testUpdateTable" />
                <testcase name="updateTable" time="5.547" classname="TestCases.testUpdateTable" />
      
</testsuite>
